// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDz4hLpedmT67R9OdITjmRD0l4rJ34sJ7E',
    appId: '1:878804260991:web:c5d75f3dc547402709074a',
    messagingSenderId: '878804260991',
    projectId: 'ecommerceapp-4c7a1',
    authDomain: 'ecommerceapp-4c7a1.firebaseapp.com',
    storageBucket: 'ecommerceapp-4c7a1.appspot.com',
    measurementId: 'G-NFC2QKMNNQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzbkZy5aZx5j08OLut4hX7J5VG7xkWLyA',
    appId: '1:878804260991:android:2a106e5b34b7371709074a',
    messagingSenderId: '878804260991',
    projectId: 'ecommerceapp-4c7a1',
    storageBucket: 'ecommerceapp-4c7a1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzceDDrj4zSicaI_8p6URYqwDhIQM5x24',
    appId: '1:878804260991:ios:3caa230ae492745209074a',
    messagingSenderId: '878804260991',
    projectId: 'ecommerceapp-4c7a1',
    storageBucket: 'ecommerceapp-4c7a1.appspot.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzceDDrj4zSicaI_8p6URYqwDhIQM5x24',
    appId: '1:878804260991:ios:c6d2bdbf4a39b20b09074a',
    messagingSenderId: '878804260991',
    projectId: 'ecommerceapp-4c7a1',
    storageBucket: 'ecommerceapp-4c7a1.appspot.com',
    iosBundleId: 'com.example.ecommerceApp.RunnerTests',
  );
}
